# Generated by Django 2.2.3 on 2019-07-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specializations',
            field=models.TextField(max_length=1000),
        ),
    ]
