# Generated by Django 2.2.3 on 2019-07-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190709_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='years_experience',
        ),
    ]
