# Generated by Django 2.2.3 on 2019-07-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_years_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo1',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo2',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo3',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo4',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo5',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo6',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
