# Generated by Django 2.2.3 on 2019-07-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190710_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='licenses',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
